# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1564, 724)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.find_line = QtWidgets.QLineEdit(self.layoutWidget)
        self.find_line.setObjectName("find_line")
        self.verticalLayout.addWidget(self.find_line)
        self.tree_widget = QtWidgets.QTreeWidget(self.layoutWidget)
        self.tree_widget.setObjectName("tree_widget")
        self.verticalLayout.addWidget(self.tree_widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_entry_button = QtWidgets.QPushButton(self.layoutWidget)
        self.add_entry_button.setObjectName("add_entry_button")
        self.horizontalLayout.addWidget(self.add_entry_button)
        self.delete_entry_button = QtWidgets.QPushButton(self.layoutWidget)
        self.delete_entry_button.setObjectName("delete_entry_button")
        self.horizontalLayout.addWidget(self.delete_entry_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.center_layout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.center_layout.setContentsMargins(0, 0, 0, 0)
        self.center_layout.setObjectName("center_layout")
        self.center_view = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.center_view.sizePolicy().hasHeightForWidth())
        self.center_view.setSizePolicy(sizePolicy)
        self.center_view.setMinimumSize(QtCore.QSize(500, 500))
        self.center_view.setBaseSize(QtCore.QSize(180, 180))
        self.center_view.setText("")
        self.center_view.setAlignment(QtCore.Qt.AlignCenter)
        self.center_view.setObjectName("center_view")
        self.center_layout.addWidget(self.center_view)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.prev_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.prev_button.setObjectName("prev_button")
        self.horizontalLayout_2.addWidget(self.prev_button)
        self.next_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.next_button.setObjectName("next_button")
        self.horizontalLayout_2.addWidget(self.next_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.center_layout.addLayout(self.horizontalLayout_2)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.editor_layout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.editor_layout.setContentsMargins(0, 0, 0, 0)
        self.editor_layout.setObjectName("editor_layout")
        self.metadata_layout = QtWidgets.QVBoxLayout()
        self.metadata_layout.setObjectName("metadata_layout")
        self.name_line = QtWidgets.QLineEdit(self.layoutWidget2)
        self.name_line.setObjectName("name_line")
        self.metadata_layout.addWidget(self.name_line)
        self.synonym_list_line = QtWidgets.QLineEdit(self.layoutWidget2)
        self.synonym_list_line.setObjectName("synonym_list_line")
        self.metadata_layout.addWidget(self.synonym_list_line)
        self.commonname_list_line = QtWidgets.QLineEdit(self.layoutWidget2)
        self.commonname_list_line.setObjectName("commonname_list_line")
        self.metadata_layout.addWidget(self.commonname_list_line)
        self.locality_list_line = QtWidgets.QLineEdit(self.layoutWidget2)
        self.locality_list_line.setObjectName("locality_list_line")
        self.metadata_layout.addWidget(self.locality_list_line)
        self.tag_list_line = QtWidgets.QLineEdit(self.layoutWidget2)
        self.tag_list_line.setObjectName("tag_list_line")
        self.metadata_layout.addWidget(self.tag_list_line)
        self.desc_edit = QtWidgets.QPlainTextEdit(self.layoutWidget2)
        self.desc_edit.setObjectName("desc_edit")
        self.metadata_layout.addWidget(self.desc_edit)
        self.vendor_list_line = QtWidgets.QLineEdit(self.layoutWidget2)
        self.vendor_list_line.setText("")
        self.vendor_list_line.setObjectName("vendor_list_line")
        self.metadata_layout.addWidget(self.vendor_list_line)
        self.editor_layout.addLayout(self.metadata_layout)
        self.save_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.save_button.setObjectName("save_button")
        self.editor_layout.addWidget(self.save_button)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_label.sizePolicy().hasHeightForWidth())
        self.status_label.setSizePolicy(sizePolicy)
        self.status_label.setMaximumSize(QtCore.QSize(16777215, 44))
        self.status_label.setText("")
        self.status_label.setObjectName("status_label")
        self.gridLayout.addWidget(self.status_label, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1564, 45))
        self.menubar.setObjectName("menubar")
        self.menuhere = QtWidgets.QMenu(self.menubar)
        self.menuhere.setObjectName("menuhere")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.menuhere.addAction(self.actionSave)
        self.menuhere.addAction(self.actionSave_as)
        self.menuhere.addAction(self.actionExport)
        self.menuhere.addAction(self.actionExit)
        self.menubar.addAction(self.menuhere.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tree_widget.headerItem().setText(0, _translate("MainWindow", "Family"))
        self.add_entry_button.setText(_translate("MainWindow", "+"))
        self.delete_entry_button.setText(_translate("MainWindow", "-"))
        self.prev_button.setText(_translate("MainWindow", "<"))
        self.next_button.setText(_translate("MainWindow", ">"))
        self.save_button.setText(_translate("MainWindow", "Save Entry"))
        self.menuhere.setTitle(_translate("MainWindow", "Fi&le"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Sa&ve as..."))
        self.actionExit.setText(_translate("MainWindow", "E&xit"))
        self.actionExport.setText(_translate("MainWindow", "&Export"))

